Improve code readability and update requirements
biplap-sarkar/pylimit pull request #7
Opened 2019-11-20 18:43 UTC by joaomedeiros95

- Update Redis version to 3.3.11 (the last one);
- Correct the max line size using pep8 convention;
- Add a new parameter to attempt that is the timestamp if the user wants to fix the timestamp between attempts

2019-11-23 16:29 UTC, biplap-sarkar requested changes

2019-11-23 16:29 UTC, biplap-sarkar commented on pylimit/tests/test_pylimit.py
>          limit = PyRateLimit()
Thanks for the pull request. This pull request is also introducing a breaking change where constructor without arguments is not valid anymore. As a result, tests are not working anymore. Will it be possible to update constructor arguments to that tests don't fail?

2019-11-23 17:32 UTC, biplap-sarkar commented
Will it be possible to update the readme as well? The current example won't be valid anymore

2019-11-25 13:54 UTC, joaomedeiros95 commented
Thanks for the feedback @biplap-sarkar, all of the changes have been made.

2019-11-26 02:36 UTC, biplap-sarkar approved these changes

2019-11-26 02:36 UTC, merged

2021-04-20 09:00 UTC, rootux commented
@biplap-sarkar This requires a new release as now the README states that you initialize using PyRateLimit(period=1,limit=10) but in fact the latest release is not updated with the README